# Generated by Django 6.0.7 on 2026-07-25 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('planned_duration', models.IntegerField()),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='planned', max_length=20)),
                ('is_carryover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PauseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_category', models.CharField(max_length=100)),
                ('custom_note', models.TextField(blank=True, default='')),
                ('pause_duration_minutes', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_logs', to='tasks.focussession')),
            ],
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Development', 'Development'), ('Design', 'Design'), ('Research', 'Research'), ('Writing', 'Writing'), ('Other', 'Other')], default='Development', max_length=50)),
                ('estimated_minutes', models.IntegerField()),
                ('session_duration', models.IntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='focussession',
            name='task_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.taskplan'),
        ),
    ]
